### ISSUE TITLE
Version Conflict

### ISSUE THREAD

**Issue by dylan-k** [snaptortoise/jekyll-pinboard-plugin#2]
After adding jekyll-pinboard to the plugins list in the config file, and after doing ``gem install jekyll-pinboard`` an error occurs during ``jekyll serve``:

'Unable to activate jekyll-pinboard-0.2.1, because jekyll-3.8.5 conflicts with jekyll (~> 2.0)'

**Comment by georgemandis** [comment]
Strange. I had to upgrade my version of jekyll, but I never ran into this error.

I'll update the gemspec to allow newer, backwards compatible versions. We'll see if that helps.

**Comment by georgemandis** [comment]
Okay, I updated the gem to be a bit more lenient about which versions of `jekyll` it's compatible with. Try it again and let me know. If you're still having issues let me know what version of Ruby you're using?

**Comment by dylan-k** [comment]
I'm still getting an error. The full error message from Ruby is: 'Unable to activate jekyll-pinboard-0.2.2, because jekyll-3.8.5 conflicts with jekyll (~> 2.0, >= 2.0.1)' 

Using Ruby 2.6.0

**Comment by georgemandis** [comment]
Hmm. I'm able to get it working with Jekyll 3.8.5 and Ruby 2.5.3. Can you try the following steps and see if you run into the same error?

- In an empty folder run `jekyll new .`
- Go ahead and try running `jekyll serve` at this point and make sure it's working
- Add `jekyll-pinboard` to the `plugins` array in `_config.yml`
- Run `gem install jekyll-pinboard`
- Add `gem "jekyll-pinboard"` to the `:jekyll_plugins` group  in your `Gemfile`
- Run `bundle instal`
- In the `_config.yml` file add the `pinboard` array that contains your username:token and the tags you'd like to pull in (See README file in this repo)

I worked for me after running all of those steps. I'm going to go ahead and bump the version of Jekyll to a later one due a a security vulnerability found in older versions, but let me know if this works for you first.

**Comment by dylan-k** [comment]
Yes this is working for me. Thanks for the help. This seems to be resolved now.

 

On 2019-01-07, 11:46 AM, "George Mandis" <notifications@github.com> wrote:

 

Hmm. I'm able to get it working with Jekyll 3.8.5 and Ruby 2.5.3. Can you try the following steps and see if you run into the same error?

·         In an empty folder run jekyll new .

·         Go ahead and try running jekyll serve at this point and make sure it's working

·         Add jekyll-pinboard to the plugins array in _config.yml

·         Run gem install jekyll-pinboard

·         Add gem "jekyll-pinboard" to the :jekyll_plugins group in your Gemfile

·         Run bundle instal

·         In the _config.yml file add the pinboard array that contains your username:token and the tags you'd like to pull in (See README file in this repo)

I worked for me after running all of those steps. I'm going to go ahead and bump the version of Jekyll to a later one due a a security vulnerability found in older versions, but let me know if this works for you first.

**Comment by georgemandis** [comment]
Happy to hear! I'm going to close this then.
