### ISSUE TITLE
A New Warning Message Appears

### ISSUE THREAD

**Issue by dylan-k** [snaptortoise/jekyll-pinboard-plugin#3]
The plugin works great, and thank you for that by the way. I did start seeing a new warning though. I have the plugin installed in the plugins folder.

```
jekyll-pinboard.rb:14: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
```

**Comment by georgemandis** [comment]
Thanks @dylan-k. What version of Ruby are you using? What operating system? I'm using 2.5 and it doesn't throw that warning, but it looks like 2.7+ might do this.

I think all you have to do is simply replace `open` on line 14 with `URI.open`.  Can you try that locally and let me know if the warning goes away? 

I tried to upgrade Ruby myself and test, but I'm on macOS and haven't touched it in a log time, and there are a lot of hoops to jump through.

**Comment by dylan-k** [comment]
My Ruby version is:
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]

I'm on Ubuntu 18.04

I made the edit you suggested on line 14, the warning went away.

**Comment by georgemandis** [comment]
Thanks @dylan-k! I'll updated the gem when I get a moment, but this is the fix. Thanks for opening the issue.
